cc_binary(
    name = "llvm-mc-extract",
    srcs = [
      "llvm-mc-extract.cpp",
    ],
    deps = [
      "@llvm-project//llvm:Support",
      "@llvm-project//llvm:AllTargetsDisassemblers",
      "@llvm-project//llvm:MC",
      "@llvm-project//llvm:Target",
    ]
)

