cc_binary(
    name = "llvm-mc-bench",
    srcs = [
      "llvm-mc-bench.cpp",
    ],
    deps = [
      "@llvm-project//llvm:Support",
      "@llvm-project//llvm:AllTargetsAsmParsers",
      "@llvm-project//llvm:MC",
      "@llvm-project//llvm:Target",
    ]
)

