name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CC: gcc-13
      CXX: g++-13

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: setup bazelisk
      uses: doppelganger113/bazelisk-setup-action@v1.0.5
    - name: setup mold
      run: sudo apt update && sudo apt -yqq install mold
    - name: install gcc 13
      run: sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/ppa && sudo apt update && sudo apt install -yqq gcc-13 g++-13
    - name: cache
      uses: actions/cache@v3
      with:
        path: ./bzl-cache
        key: scratch-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          scratch-${{ runner.os }}
    - name: build
      run: bazel build --config=ci //...
    - name: lit tests
      run: bazel test --config=ci //tests/...
