name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
  merge_group:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: setup bazelisk
      uses: doppelganger113/bazelisk-setup-action@v1.0.5
    - name: setup mold
      run: sudo apt update && sudo apt -yqq install mold
    - name: cache
      uses: actions/cache@v3
      with:
        path: ./bzl-cache
        key: scratch-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          scratch-${{ runner.os }}
    - name: build
      run: bazel build --config=ci //...
    - name: lit tests
      run: bazel test --config=ci //tests/...
    - name: generate tools archive
      run: bazel build --config=ci //:llvm_ml_tools
    - uses: actions/upload-artifact@v3
      with:
        name: tools
        path: bazel-out/k8-fastbuild/bin/llvm_ml_tools.tar.zst 
    - uses: actions/upload-artifact@v3
      with:
        name: python_wheel
        path: bazel-out/k8-fastbuild/bin/llvm_ml-*.whl
